# Generated by Django 3.2.5 on 2021-08-11 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_project_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='count',
        ),
    ]
