# Generated by Django 3.2.5 on 2021-08-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0004_remove_project_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
