# Generated by Django 3.2.5 on 2021-08-11 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedapp', '0002_feed_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='image',
        ),
    ]
